/**
 * app/(brand)/brief/[id]/page.tsx — Structured brief detail view.
 * Reads from Supabase when the id is a real UUID; falls back to the seeded
 * demo brief keyed by slug (demo, demo-ugc, …) so the demo never dead-ends.
 */
import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft, Sparkles, Users, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { getBriefById, getSupabaseAdmin } from "@/lib/db/client";
import type { Brief } from "@/lib/types";
import { getDemoBriefByParam } from "@/app/demoBrief";

export const dynamic = "force-dynamic";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

async function loadBrief(id: string): Promise<Brief | null> {
  if (UUID_RE.test(id)) {
    try {
      return await getBriefById(getSupabaseAdmin(), id);
    } catch (err) {
      console.warn("[brief page] DB load failed:", String(err));
    }
  }
  return getDemoBriefByParam(id);
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="grid grid-cols-3 gap-4 border-b py-3 text-sm last:border-b-0">
      <dt className="font-semibold uppercase tracking-wide text-muted-foreground text-xs pt-0.5">{label}</dt>
      <dd className="col-span-2">{children}</dd>
    </div>
  );
}

export default async function BriefDetailPage({ params }: { params: { id: string } }) {
  const brief = await loadBrief(params.id);
  if (!brief) notFound();

  return (
    <div className="min-h-screen">
      <header className="border-b bg-white/70 backdrop-blur">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <Link href="/dashboard" className="flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground">
            <ChevronLeft className="h-4 w-4" /> Dashboard
          </Link>
          <span className="flex items-center gap-2 font-bold">
            <Sparkles className="h-4 w-4 text-primary" /> PromptFolio
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-4xl space-y-6 px-6 py-10">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight">
              <FileText className="h-5 w-5 text-primary" /> {brief.campaign_objective || "Creative brief"}
            </h1>
            <p className="mt-1 max-w-xl text-sm italic text-muted-foreground">“{brief.raw_input}”</p>
          </div>
          <Badge variant={brief.status === "matched" ? "success" : "secondary"}>{brief.status}</Badge>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">Structured brief</CardTitle>
            <CardDescription>Generated by the AI brief builder and editable at creation time.</CardDescription>
          </CardHeader>
          <CardContent>
            <dl>
              <Row label="Content type">{brief.content_type}</Row>
              <Row label="Style">{brief.style}</Row>
              <Row label="Duration / Ratio">{brief.duration} · {brief.aspect_ratio}</Row>
              <Row label="Platform">{brief.platform}</Row>
              <Row label="Audience">{brief.target_audience}</Row>
              <Row label="Visual direction">{brief.visual_direction}</Row>
              <Row label="Required tools">
                <div className="flex flex-wrap gap-1.5">
                  {brief.required_tools.map((t) => <Badge key={t} variant="outline">{t}</Badge>)}
                </div>
              </Row>
              <Row label="Commercial usage">{brief.commercial_usage}</Row>
              <Row label="Deliverables">
                <ul className="list-disc pl-4">
                  {brief.deliverables.map((d) => <li key={d}>{d}</li>)}
                </ul>
              </Row>
              <Row label="Constraints">
                <ul className="list-disc pl-4">
                  {brief.constraints.map((c) => <li key={c}>{c}</li>)}
                </ul>
              </Row>
            </dl>
          </CardContent>
        </Card>

        <div className="flex justify-end">
          <Link href={`/brief/${brief.id}/matches`}>
            <Button size="lg" className="gap-2">
              <Users className="h-4 w-4" /> View ranked creator matches
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
