/**
 * lib/ai/explainer.ts — Explainable match narratives.
 * Template bullets are always available (generated by the engine); this module
 * optionally polishes them with GPT-4o and degrades gracefully to templates.
 */
import OpenAI from "openai";
import type { Brief, CreatorMatch, CreatorProfile, ExplanationPayload } from "../types";

interface ExplainInput {
  brief: Brief;
  profile: CreatorProfile;
  match: CreatorMatch;
}

export async function explainMatch(input: ExplainInput): Promise<string[]> {
  const templateBullets: string[] =
    input.match.explanation?.bullets ?? fallbackBullets(input.brief, input.profile);

  try {
    const polished = await polishWithLLM(templateBullets, input);
    return polished.length >= 4 ? polished.slice(0, 5) : templateBullets;
  } catch (err) {
    console.warn("[explainer] LLM polish failed, using template bullets:", String(err));
    return templateBullets;
  }
}

async function polishWithLLM(bullets: string[], input: ExplainInput): Promise<string[]> {
  const key = process.env.OPENAI_API_KEY;
  if (!key) throw new Error("OPENAI_API_KEY not configured");
  const openai = new OpenAI({ apiKey: key });

  const completion = await openai.chat.completions.create({
    model: process.env.OPENAI_MODEL ?? "gpt-4o",
    response_format: { type: "json_object" },
    temperature: 0.3,
    messages: [
      {
        role: "system",
        content:
          "You rewrite creator-match explanations for brand buyers. Keep every factual claim; make each bullet crisp and specific. Respond ONLY with JSON: {\"bullets\": string[]} of 4-5 items.",
      },
      {
        role: "user",
        content: JSON.stringify({
          brief: {
            content_type: input.brief.content_type,
            style: input.brief.style,
            platform: input.brief.platform,
            commercial_usage: input.brief.commercial_usage,
          },
          creator: input.profile.creator.display_name,
          score: input.match.total_score,
          draft_bullets: bullets,
        }),
      },
    ],
  });

  const text = completion.choices[0]?.message?.content ?? "{}";
  const parsed = JSON.parse(text) as { bullets?: unknown };
  if (!Array.isArray(parsed.bullets)) throw new Error("Bad explainer shape");
  return parsed.bullets.filter((b): b is string => typeof b === "string" && b.length > 0);
}

/** Last-resort bullets when no explanation payload exists on the row. */
export function fallbackBullets(
  brief: Brief,
  profile: CreatorProfile,
  explanation?: ExplanationPayload | null,
): string[] {
  const tools = explanation?.matched_tools ?? profile.tools.map((t) => t.tool).slice(0, 3);
  const specs =
    explanation?.matched_specializations ??
    profile.specializations.map((s) => s.specialization).slice(0, 1);
  return [
    specs.length > 0
      ? `Creator specializes in ${specs.join(", ")}.`
      : `Experienced AI creator (${profile.creator.years_experience} yrs).`,
    tools.length > 0 ? `Uses ${tools.join(", ")} for ${brief.content_type.toLowerCase()} work.` : "",
    explanation?.top_portfolio_title
      ? `Relevant portfolio piece: "${explanation.top_portfolio_title}" (${brief.aspect_ratio}).`
      : `Has ${profile.portfolios.length} portfolio examples on file.`,
    `Declared rights coverage aligns with "${brief.commercial_usage}".`,
    profile.verified_badge
      ? "Verified AI Creator badge (3+ evidence-backed signals)."
      : "Self-declared profile — verification signals pending.",
  ].filter(Boolean);
}
